



title: Portfolio

url: "http://jmstan.github.io/portfolio4/"

baseurl: "portfolio4/"
permalink: pretty

collections:
    portfolio:
        output: true
    gallery:
        output: true
    altBlog:
        output: true