



title: Portfolio

url: "http://jmstan.github.io/portfolio4/"

baseurl: "portfolio4/"
permalink: pretty

navigation:
 - title: Work
   baseurl: index
 - title: About
   baseurl: /about
 - title: Blog
   baseurl: /blog
 - title: Studies
   baseurl: /studies

collections:
    portfolio:
        output: true
    gallery:
        output: true
    altBlog:
        output: true