



title: my Github Site

url: "http://jmstan.github.io/my-github-repo/"

baseurl: "my-github-repo/"
permalink: pretty

collections:
    portfolio:
        output: true
    gallery:
        output: true
    altBlog:
        output: true