



title: Portfolio

url: "http://jmstan.github.io/portfolio4/"

baseurl: "portfolio4/"
permalink: pretty

navigation:
 - title: Work
   url: portfolio4/index
 - title: About
   url: portfolio4/about
 - title: Blog
   url: portfolio4/blog
 - title: Studies
   url: portfolio4/studies

collections:
    portfolio:
        output: true
    gallery:
        output: true
    altBlog:
        output: true