



title: Portfolio

#url: "janestanton.tld"
#url: "janestanton.co/"
url: "http://jmstan.github.io/portfolio4"




baseurl: "/porfolio4"
#baseurl: "/"
#baseurl: "/portfolio4"
permalink: pretty



navigation:
 - title: Work
   url: work
 - title: About
   url: about
 - title: Blog
   url: blog
 - title: Studies
   url: studies

collections:
    portfolio:
        output: true
    gallery:
        output: true
    altBlog:
        output: true