



title: Portfolio

url: "http://jmstan.github.io/portfolio4/"

baseurl: "portfolio4/"
permalink: pretty

navigation:
 - title: Work
   url: index
 - title: About
   url: about
 - title: Blog
   url: blog
 - title: Studies
   url: studies

collections:
    portfolio:
        output: true
    gallery:
        output: true
    altBlog:
        output: true