#markdown: rdiscount
#pygments: true
#auto: true

#ftp_host: 'janestanton.co'
#ftp_dir: '/web/content'
#ftp_passive: false

# optional
#ftp_port: 21                  # default 21
#ftp_username: 'stanjane'     # default read from stdin
#ftp_password: 'your_ftp_pass' # default read from stdin




title: Portfolio

url: "http://jmstan.github.io"
#url: "janestanton.co/"



#baseurl: "portfolio4"
baseurl: "/portfolio4"
permalink: pretty



navigation:
 - title: Work
   url: work
 - title: About
   url: about
 - title: Blog
   url: blog
 - title: Studies
   url: studies

collections:
    portfolio:
        output: true
    gallery:
        output: true
    altBlog:
        output: true